# Generated by Django 3.0.6 on 2020-05-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('imageUri', models.ImageField(blank=True, null=True, upload_to='')),
                ('jerseyNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logoUri', models.ImageField(blank=True, null=True, upload_to='')),
                ('clubState', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(blank=True, default=0, null=True)),
                ('runs', models.IntegerField(blank=True, default=0, null=True)),
                ('highestScore', models.IntegerField(blank=True, default=0, null=True)),
                ('fifties', models.IntegerField(blank=True, default=0, null=True)),
                ('hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(blank=True, max_length=10, null=True)),
                ('team2', models.CharField(blank=True, max_length=10, null=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
