# Generated by Django 3.0.6 on 2020-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200517_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='imageUri',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logoUri',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
