# Generated by Django 3.0.6 on 2020-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200517_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='imageUri',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='logoUri',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
